### ISSUE TITLE
Go 1.7 and 1.8 are failing in TravisCI

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/amazon-ecr-credential-helper#139]
```
$ make get-deps
go get github.com/tools/godep
go get golang.org/x/tools/cmd/cover
go get github.com/golang/mock/mockgen
go get golang.org/x/tools/cmd/goimports
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
# golang.org/x/tools/go/internal/packagesdriver
../../../golang.org/x/tools/go/internal/packagesdriver/sizes.go:91: undefined: types.SizesFor
make: *** [get-deps] Error 2
The command "make get-deps" failed and exited with 2 during .
```

We should probably remove 1.7 and 1.8 from TravisCI since they're no longer in supported in Go's [release policy](https://golang.org/doc/devel/release.html#policy) (Go 1.10 and Go 1.11 are supported, anything older is not).  We also can't really build with 1.6 anymore, so the README also needs to be updated to have a current set of requirements.
